# -*- coding: utf-8 -*-
"""
Created on Thu Jun 28 15:16:38 2018

@author: DongliangLu
"""

#add orginzation type
import pickle


org_pickle=r"C:\Users\DongliangLu\Desktop\Columbia\research\CBS\lobby\data_cleaned"+"\\SEC_meeting_total.pickle"
with open(org_pickle,"rb") as f:
    tem=pickle.load(f, encoding='latin1')

org_clean=set(tem.keys())

new_org=["Prudential","Renaissance","Putnam","American Express",
         "Japanese Bankers Assocation","Invesco","CalPERS","Vanguard",
         "CIEBA","FTN","FSA","NACL","NAMIC","UKRCBC","TCW","BBVA","Western Asset Management",
         "Union Asset",]
new_org=set(new_org)
org_clean=org_clean|new_org
org_for_see=list(org_clean)
org_for_see.sort()




org_tag_add=r"C:\Users\DongliangLu\Desktop\Columbia\research\CBS\lobby\data_cleaned"
org_tag_add+="\\org_tag.txt"
#with open(org_tag_add, 'w') as f:
#    for org in org_for_see:
#        f.write('"'+org+'":'+" ,")
#        f.write("\n")
    
    
#label:
label_dic={0:"congress",
           1:"government",
           2:"big financial banks and am companies",
           3:"other financial institution",
           4:"real estate",
           5:"insurance",
           6:"law/lobby firm",
           7:"other accociation",
           8:"other",
           9:"financial association",
           10:"university"
        }



org_tag={
"AALU": 7,
"AARP": 7,
"ABA": 8,
"ABC": 7,
"ACLI":7 ,
"AFGI": 7,
"AFLCIO":7 ,
"AFP": 7,
"AFS": 7,
"AFSCME": 3,
"AII": 7,
"AIMA":9 ,
"APA": 7,
"APGA":7 ,
"API": 7,
"ASF": 7,
"ATA": 7,
"AVX": 8,
"Advance Micro Devices":8 ,
"Albourne Partners Limite": 8,
"American Express": 8,
"Americans for Financial Reform": 7,
"Ameriprise": 3,
"Anadarko Petroleum Corporation":8 ,
"Annuity Insurers": 5,
"Apple": 8,
"Arnold Porter":6 ,
"Assured Guaranty": 3,
"Australian Banks": 3,
"BBA": 7,
"BBVA":3 ,
"BCAM":3 ,
"BDA": 3,
"BHP Billiton": 8,
"BNY Mellon": 2,
"BP":8 ,
"Baker":6 ,
"Bank for International Settlements":9 ,
"Bank of America Merrill Lynch": 2,
"Bank of Oliver Wym": 3,
"Barclays": 2,
"Bearm": 6,
"Benchmark Solutions": 3,
"Best Buy": 3,
"Better Markets":9 ,
"BlackRock": 2,
"Bloomberg": 3,
"BlueMountain": 3,
"Boston University": 10,
"Broadridge": 3,
"CFA": 9,
"CFP": 7,
"CFTC":1 ,
"CIEBA": 9,
"CII": 9,
"CME": 2,
"CRE":9 ,
"CSA": 3,
"CSBS": 7,
"CSFME":9 ,
"CalPERS":7 ,
"Caldwell Berkowitz":6 ,
"Calvert":3 ,
"Canadian Banks and the Canadian Bankers Association": 9,
"Capital Alph":3 ,
"Capstone": 8,
"Center for Capital Markets Competitiveness": 9,
"Center on Executive Compensatio": 7,
"Charles Schwab":3 ,
"Chatham Financial":3 ,
"Chesapeake Management": 3,
"Citadel": 2,
"Citigroup":2 ,
"Cleary Gottlieb": 6,
"Cliff Palefsky and Michael Rubi":6 ,
"Coalition for Derivatives End Users":9 ,
"Conference Board Governance Center": 7,
"ConocoPhillips": 8,
"Consumer Federation of America": 7,
"Corporate Library":7 ,
"Costco Wholesale Corporation": 8,
"County and Municipal Employees": 7,
"Covington Burling":6 ,
"Credit Derivatives Product Companies": 3,
"Credit Research": 3,
"Credit Roundtable and Fixed Income Forum": 9,
"Credit Suisse": 2,
"Creditex": 3,
"Cronimet Central Africa AG": 8,
"Cypress Group and Koch Companies Public Sector":8 ,
"DBRS": 8,
"DE Shaw": 2,
"DLA Piper": 6,
"Data Explorers":8 ,
"Davis Polk Wardwell":6 ,
"Dealer industry": 9,
"Debevoise Plimpton":6 ,
"Dechert": 6,
"Dek": 8,
"Delta Strategy Group":3 ,
"Delves Group": 8,
"Democratic Republic of the Congo": 7,
"Demos": 7,
"Densus Group": 8,
"Depository Trust and Clearing Corporation": 3,
"Derivative Project":9 ,
"Deutsche Bank": 2,
"Donelso":8 ,
"Dunn and Crutcher":6 ,
"EFAMA": 6,
"EITI": 7,
"ERISA": 1,
"ESeclending":3 ,
"EU Economic Counselors": 7,
"EarthRights International": 7,
"Edward Jones":3 ,
"Edward Rose":8 ,
"Elkins Kalt": 8,
"Embassy of Jap": 7,
"Emerson Electric Company":8 ,
"Enough Project":7 ,
"Equile": 8,
"European Commissio":7 ,
"European Parliament":7 ,
"Extractive Industries Transparency Initiative": 7,
"Exxon Mobil":8 ,
"FINRA": 9,
"FIRA": 9,
"FPA":7,
"FPC":9 ,
"FSA": 9,
"FSF":3 ,
"FSI":9 ,
"FSR": 9,
"FTN": 3,
"Federated Investors":3 ,
"Fidelity":2 ,
"Fiduciary Standar":3 ,
"First Clearing": 3,
"Fitch Ratings": 3,
"French Ministry of Foreign Affairs and the Embassy of France":7 ,
"Fund Democracy":9 ,
"GE": 3,
"GETCO":8 ,
"General Counsel":6 ,
"General Electric": 8,
"Genworth Financial":3 ,
"Gibso":6 ,
"Gibson Dunn":6 ,
"Glass Lewis": 8,
"Global Witness":7 ,
"Goldman Sachs": 2,
"Gotshal Manges": 6,
"Government of Singapore Investment Corporation": 7,
"Grassroots Reconciliation Group": 7,
"GraviT": 8,
"Greenlining Institute": 7,
"Greg Smith": 8,
"Grohovsky Whipple": 6,
"Groom Law Group": 6,
"Grosvenor Capital Management":3 ,
"Gunderson Dettmer":6 ,
"HBK":3 ,
"HSBC": 2,
"HUA": 7,
"HVP": 8,
"Hewlett-Packard Company": 8,
"Hillsman Palefsky":6 ,
"IAA": 7,
"IBM": 8,
"ICE": 1,
"ICI": 3,
"IFS": 7,
"IIB":9 ,
"IIF": 9,
"ISDA": 9,
"ISLA":9 ,
"ITIC": 7,
"ITRI": 8,
"Implementation Discussio": 8,
"Individual": 8,
"Intercontinental Exchange": 3,
"International Banks": 9,
"International Brotherhood of Teamsters": 6,
"International Interfaith Investment Group": 7,
"International Precious Metals Institute and Materials Management Corp": 8,
"International Union of North America":7 ,
"Invesco": 3,
"Investment Company Institute":3 ,
"JA":7 ,
"JC Penney": 3,
"JP Morgan":2 ,
"Japanese Bankers Assocation": 7,
"Javelin Capital Markets": 3,
"Jeff Merkley": 0,
"Jefferies":3 ,
"Jewelers Vigilance Committee": 7,
"Johnson Johnso":8 ,
"Kalorama Partners": 8,
"Kenney McCafferty": 6,
"KfW Bankengruppe": 3,
"Klein Saks Group": 3,
"LCH": 3,
"LFSA":7 ,
"LPL Financial":3 ,
"LSTA":9 ,
"Labaton Sucharow": 3,
"Labor Union":7 ,
"Law office of Baker": 6,
"Leahy": 0,
"Levin Institute": 7,
"Lowes Companies":8 ,
"MEFA": 7,
"MFA": 9,
"MICA": 3,
"MSRB": 9,
"Mahesh Kotech":8 ,
"Malaysia Smetling Corporation": 8,
"MarkitSERV": 3,
"Mayer Brown": 6,
"McGui": 8,
"MetLife": 5,
"Millennium": 2,
"Minerals Supply Afric": 8,
"Morgan Stanley": 2,
"Mortgage Bankers Association": 9,
"Motorol": 8,
"Municipal Entities":3 ,
"NAAC": 7,
"NACL": 8,
"NACUBO": 7,
"NADA":9 ,
"NAIC": 5,
"NAIFA": 5,
"NAM":8,
"NAMIC": 5,
"NAPFA":7 ,
"NASAA":9 ,
"NBF": 9,
"NCL":7 ,
"NFS": 9,
"NJSA": 7,
"NMA": 7,
"NRF": 7,
"NRGI": 7,
"NVCA": 9,
"NYSE": 3,
"Nasdaq": 3,
"National Whistleblowers Center": 6,
"Natixis":3 ,
"Natural Resources": 8,
"New York Chapter of the Society for Corporate Secretaries and Governance Professional": 7,
"Newedge": 3,
"Noble Energy":8 ,
"Nomura":2 ,
"Northern Trust": 3,
"Not-For-Profit Energy End User Coalitio":7 ,
"OCC": 1,
"OTC Derivatives Regulators Forum": 9,
"Occupy the SEC": 9,
"Ogilvy Government Relations": 6,
"Omgeo":3 ,
"One Campaig":6 ,
"Oracle":8 ,
"Oxfam Americ": 7,
"PIABA": 7,
"PIMCO": 3,
"PNC":3 ,
"PWYP":7 ,
"Pan-Canadian Investors Committee": 7,
"Paul Volcker": 0,
"Pennsylvania Public School":10 ,
"Pew Charitable Trusts":7 ,
"Pickard Djinis":6 ,
"Pivot": 8,
"Primeric": 5,
"Private Equity Growth Capital Council": 9,
"Private Investors Coalitio":9 ,
"Professor Barbara Black":10 ,
"Professor Darrell Duffie": 10,
"Professor James Angel of Georgetown University":10 ,
"Professor Matthew Richardso":10 ,
"Professor Peter Rosenblum of Columbia University":10 ,
"Professor Simon Johnso": 10,
"Property Casualty Insurers Association of America": 5,
"Proskauer Rose": 3,
"Prudential": 5,
"Public pension plans": 7,
"Publish What You Pay Coalitio":7 ,
"Putnam":3 ,
"Quadriserv": 3,
"RBC": 2,
"RBS":3 ,
"REISA":5 ,
"RMA":9 ,
"Redwood Trust and Falcon Capital Advisors":3 ,
"Regulatory Policy": 7,
"Renaissance": 2,
"Representatives organized by the National Association of Manufacturers":7 ,
"Retail Industry Leaders Association": 7,
"Reval":3 ,
"Rich Feuer Group": 6,
"Richline Group":8 ,
"RiskMetrics Group": 3,
"Robert M Fields":6 ,
"Roosevelt Institute": 6,
"Roy Weinberger": 7,
"Royal Dutch Shell": 7,
"SCIC": 3,
"SDMA": 9,
"SEIU": 7,
"SIF": 7,
"SIFMA": 9,
"SRC": 9,
"SVB": 3,
"Senator Cardin":0 ,
"Senator Carte P Goodwi": 0,
"Senator Jeff Merkley": 0,
"Senator Merkley":0 ,
"Senator Richard Durbin":0 ,
"Senators Merkley": 0,
"Sharon Ry":8 ,
"Shell International Limite":8 ,
"Siemens Corporation": 8,
"Simon Johnso": 10,
"Slade Goldstei": 3,
"Society Generale":2 ,
"Society of Corporate Secretaries and Governance Professionals":7 ,
"Stable Value": 3,
"Staff of Senator Jeff Merkley and Senator Carl Levi":0 ,
"Standard Poors Rating Services":8 ,
"State Farm": 5,
"State Street": 3,
"State of Wisconsin Investment Boar": 3,
"Stuart D Meissner": 6,
"SunGar": 8,
"Susan Seltzer":6 ,
"Sutherl":8 ,
"Swap Financial Group": 3,
"TBAC":9 ,
"TCW": 3,
"TD Ameritrade": 3,
"TIAA-CREF": 5,
"TIW": 8,
"Target Corporation": 8,
"Thomson Reuters":8 ,
"Tiedemann Wealth Management": 3,
"Towers Watso":3 ,
"TradeWeb":3 ,
"TriOptim": 3,
"Trillium Asset Management": 3,
"Trumarx Data Partners":8 ,
"UBS": 2,
"UKRCBC":7 ,
"US Chamber of Commerce":6 ,
"US Senate Committee on Banking": 1,
"USAA":7 ,
"USB": 8,
"Udy Group":8 ,
"Union Asset": 3,
"United Nations Group of Experts": 7,
"University of Maryland": 10,
"Vanguard": 3,
"Various Buy-Side Firms": 9,
"Various pension plans": 7,
"Vogel": 3,
"WMBA": 9,
"Wal-Mart Stores": 8,
"Weil": 6,
"Wells Fargo":2 ,
"Western Asset Management": 3,
"WilmerHale": 6,
"Winston Strawn":6 ,
"Woodbine Associates": 8,
"Yale University": 10,
}


save_pickle_org_tag=r"C:\Users\DongliangLu\Desktop\Columbia\research\CBS\lobby\data_cleaned"+"\\SEC_org_tag"+".pickle"
pickle.dump(org_tag, open(save_pickle_org_tag,"wb"))   

























    